version: "3"
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./default.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - php
      - mysql
  php:
    build: ./docker/php
    volumes:
      - ./code:/code
  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    restart: always
    env_file:
      - ".env"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "8989:3306"
    volumes:
      - "./data/mysql:/var/lib/mysql"
